# Generated by Django 5.2 on 2025-04-12 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_session_meeting_id_session_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'moderator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='selector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'evaluator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EvaluatorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('evaluator', models.ForeignKey(limit_choices_to={'role': 'evaluator'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.topic')),
            ],
        ),
    ]
