# Generated by Django 5.2 on 2025-04-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_session_scheduled_by_alter_session_selector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='static/user_images/avatar.svg', null=True, upload_to='static/user_images/'),
        ),
    ]
