# Generated by Django 5.2 on 2025-04-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_image'),
    ]

    operations = [
    ]
