# Generated by Django 5.2 on 2025-04-12 09:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20250412_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluatoravailability',
            options={'ordering': ['-available_from']},
        ),
        migrations.AddField(
            model_name='evaluatoravailability',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evaluatoravailability',
            name='topic',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.topic'),
        ),
    ]
